# env should be created with mamba/conda
name: msd_6_term
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - numpy
  - scipy
  - pandas
  - numba
  - matplotlib
  - ipykernel
  - pytorch
  - torchvision
  - pip:
    - sktime
    - tsfresh
    - xgboost
